FROM    nginx

COPY    project/nginx/default.conf /etc/nginx/conf.d/
COPY    project/nginx/login.html /usr/share/nginx/html/
COPY    project/nginx/main.html /usr/share/nginx/html/
COPY    project/nginx/table.css /usr/share/nginx/html/
COPY    project/nginx/temp/* /usr/share/nginx/html/

EXPOSE  80
