FROM    nginx

COPY    default.conf /etc/nginx/conf.d/
COPY    login.html /usr/share/nginx/html/
COPY    main.html /usr/share/nginx/html/
COPY    table.css /usr/share/nginx/html/
ADD    temp/ /usr/share/nginx/html/


EXPOSE  80
